source("server/model.R", local = TRUE)
source("server/more.R",  local = TRUE)
source("server/plot.R",  local = TRUE)
source("server/table.R", local = TRUE)
source("server/reset.R", local = TRUE)

source("server/param/mu.R",    local = TRUE)
source("server/param/beta.R",  local = TRUE)
source("server/param/sigma.R", local = TRUE)
source("server/param/delta.R", local = TRUE)
