source("server/dynamic.R",    local = TRUE)
source("server/param-plot.R", local = TRUE)
source("server/model.R",      local = TRUE)
source("server/more.R",       local = TRUE)
source("server/plot.R",       local = TRUE)
source("server/reset.R",      local = TRUE)
source("server/table.R",      local = TRUE)
